### PR TITLE
Update changelog with actionlint 1.6.4 version bump

### PR DESCRIPTION
**Pull request by radomirbosak**
Adding changelog note forgotten in #2702 .

### CODE REVIEW

**Comment by dev-yakuza** [comment]
How about this?

```
New supported:

- **actionlint**  1.6.4 [#2650](https://github.com/sider/runners/pull/2650), [#2702](https://github.com/sider/runners/pull/2702)
```

**Comment by suetsuguk** [comment]
We have both adding a new linter and updating versions this time. I agree with Kim's suggestion.

**Comment by radomirbosak** [comment]
Thank you for the suggestion. I moved the Bump-PR link to the **New supported** section as you suggested.

**Review by dev-yakuza — APPROVED** [review]
LGTM 👍

**Review by suetsuguk — APPROVED** [review]
LGMT. Thank you.

**Pull request merged**
