### PR TITLE
Support npm 7

### LINKED ISSUE #1963: Support npm 7
npm 7 has beeen `latest` from `next` now.
See <https://twitter.com/npmjs/status/1352357452927393792>.

See also:
- https://docs.npmjs.com/cli/v7/commands/npm-install
- https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/
- https://github.blog/2021-02-02-npm-7-is-now-generally-available/
- https://blog.npmjs.org/post/631877012766785536/release-v700

The new version has some **breaking changes**:

image

Note: We will update the version on devon_rex actually:
https://github.com/sider/devon_rex/blob/f71549a96fe21793d0ff2e612ba81f71207cabaf/npm/package.json#L3

### PR DESCRIPTION
**Pull request by ybiquitous**
> Explain a summary, purpose, or background for this change.

This change aims to support newly npm 7. It includes important changes:

- no longer runs `yarn install`
- deprecates `npm_install: development` option
- no longer raises an error even if two lock files are present

> Refer related issues or pull requests (e.g. `Close #123` or `None`).

Close #1963 

> Check the following if needed.

- [x] Add a new entry to [CHANGELOG.md](https://github.com/sider/runners/blob/master/CHANGELOG.md) if this change is notable.

### CODE REVIEW

**Comment by ybiquitous** [comment]
@yykamei Could you please review this PR if you have time? (sorry for the big change...)

**Comment by ybiquitous** [comment]
> * deprecates `npm_install: development` option

`npm install` no longer supports `--only=development`, but perhaps we can emulate it as below:

```ruby
dev_deps = (package_json[:devDependencies] || {}).map { |name, version| [name, version].join("@") }
capture3_with_retry! "npm", "install", *cli_options, *dev_deps
```

Of course, this cannot support locked versions. So, it may be confusing for users. 🤔

**Review by yykamei — APPROVED** [review]
Awesome, the test case `yarn_lock` in `coffeelint/expectations.rb` passed :tada: 

LGTM

**Comment by ybiquitous** [comment]
Thank you for the review! 😄

**Pull request merged**
