### PR TITLE
[Misspell] Some improvements

### PR DESCRIPTION
**Pull request by ybiquitous**
I believe that the following changes can improve the usability:

- Use a correct word as an issue ID instead of an issue message.
- Save an issue's metadata: a correct word and an incorrect word.

Also, this change makes refactoring to make the code readable a bit.

### CODE REVIEW

**Comment by ybiquitous** [comment]
@yykamei What do you think about this change?

**Comment by ybiquitous** [comment]
Thank you!

**Comment by yykamei** [comment]
By the way, `Tempfile.create` typically seems the same pattern among analyzers.

**Comment by ybiquitous** [comment]
Yes, do you have any ideas?

**Comment by ybiquitous** [comment]
For example, how about this? ⬇️ 

```ruby
class Processor
  def report_file(ext: ".txt")
    Tempfile.create(["#{analyzer_id}_", ext]).path
  end
end
```

**Comment by yykamei** [comment]
:clap: Great, I like it.

**Comment by ybiquitous** [comment]
Thanks, I'll try it. 💪

**Pull request merged**
