### PR TITLE
Add .remarkrc.yml to fix dead urls error

### LINKED ISSUE #2679: [remark-lint] sometimes fails with `git-blame failed: ... The requested URL returned error: 429`
This is an example log:
```
Run remark-lint
$ remark --report vfile-reporter-json --no-color --no-stdout .
...
exit status: 0
1126 issue(s) found.
Removing issues from unchanged or untracked files...
git-blame failed: fatal: unable to access 'https://github.com/sider/runners.git/': The requested URL returned error: 429
fatal: Cannot read blob 7026d5c03d9fe17d7da746a4c2de9d120791e1a6 for path README.md
 (Runners::Workspace::Git::BlameFailed)
Writing result...
Finish analysis
remark-lint analysis failed.
Finished at 2021-09-14 05:54:28 UTC
Elapsed time: 16s
```

It looks like as if GitHub was contacted during git-blame too many times and returned an error 429: Too many requests

### PR DESCRIPTION
**Pull request by dev-yakuza**
### Summary or Background

The `changelog` file has many GitHub links, so the `remark-lint-no-dead-urls` rule in Sider recommended rules makes errors like the below. 

```
Run remark-lint
$ remark --report vfile-reporter-json --no-color --no-stdout .
...
exit status: 0
1126 issue(s) found.
Removing issues from unchanged or untracked files...
git-blame failed: fatal: unable to access 'https://github.com/sider/runners.git/': The requested URL returned error: 429
fatal: Cannot read blob 7026d5c03d9fe17d7da746a4c2de9d120791e1a6 for path README.md
 (Runners::Workspace::Git::BlameFailed)
Writing result...
Finish analysis
remark-lint analysis failed.
Finished at 2021-09-14 05:54:28 UTC
Elapsed time: 16s
```

So, I add the`skipUrlPatterns` option of `remark-lint-no-dead-urls` to ignore the GitHub links

### Issues or Pull Requests

Close #2679

### Checklist

- [] Add a new entry to [CHANGELOG.md](https://github.com/sider/runners/blob/master/CHANGELOG.md) if this change is notable.

### CODE REVIEW

**Comment by dev-yakuza** [comment]
https://sider.review/gh/repos/202486306/pulls/2650/logs/835c654a-7d5d-49df-abc6-9f35526a2ed6

Screen Shot 2021-09-15 at 16 59 07

https://sider.review/gh/repos/202486306/pulls/2683/logs/0b532250-3d4c-4c86-9048-2fd215420c1e

Screen Shot 2021-09-15 at 17 00 01

The issue count is changed from `1143` to `0` and there is no `no-dead-urls` issue. But the Sider recommended rule is not used.

**Comment by dev-yakuza** [comment]
I think using the `.remarkignore` file is better than `.remarkrc.yml`, because we can use Sider recommended rules.

https://sider.review/gh/repos/202486306/pulls/2683/logs/7506a4d5-9203-4853-b42e-4b41bb3d1966

Screen Shot 2021-09-15 at 17 19 12

**Comment by ybiquitous** [comment]
> So, I add the`skipUrlPatterns` option of `remark-lint-no-dead-urls` to ignore the GitHub links

Where?

**Comment by dev-yakuza** [comment]
@ybiquitous 
Sorry, I will modify the description.

https://github.com/sider/runners/pull/2683/commits/02b170c13c245d9e3f0f4c8530a155325e875f77#diff-47e126406d956271c983e5b22a1bc206c3106e47e1425540e4e77e2b98a4932bR1-R6

The first time, I added it. but I decided to use `.remarkignore` instead of the option because if we use the `.remarkrc.yml` file, the recommended rule is ignored. (Reason: https://github.com/sider/runners/pull/2683#issuecomment-919791166)

**Comment by ybiquitous** [comment]
How about the following file?

```yaml
plugins:
  remark-preset-lint-sider: true
  remark-validate-links: true
  remark-lint-no-dead-urls:
    skipUrlPatterns:
      - https://github.com/sider/runners/pull
      - https://github.com/sider/runners/issues
      - https://github.com/sider/runners/compare
      - https://github.com/sider/devon_rex/compare
```

**Comment by dev-yakuza** [comment]
@ybiquitous 
Looks good! I will try it.

**Review by ybiquitous — APPROVED** [review]
👍🏼

**Comment by ybiquitous** [comment]
Please rewrite the PR title.

**Review by suetsuguk — APPROVED** [review]
I have verified the analysis log for this commit. Looks good. Thank you.

**Review by radomirbosak — APPROVED** [review]
Thank you for this!

**Pull request merged**
