### PR TITLE
[Flake8] Enable Sider's recommended set of rules

### PR DESCRIPTION
**Pull request by sleeeto**
> Explain a summary, purpose, or background for this change.

We enable Sider's recommended ruleset of Flake8.

> Refer related issues or pull requests (e.g. `Close #123` or `None`).

None.

> Check the following if needed.

- [x] Add a new entry to [CHANGELOG.md](https://github.com/sider/runners/blob/master/CHANGELOG.md) if this change is notable.

### CODE REVIEW

**Comment by sleeeto** [comment]
@ybiquitous Please check it.

**Comment by ybiquitous** [comment]
[question]
- Can you use [PULL_REQUEST_TEMPLATE.md](https://github.com/sider/runners/blob/2c74c40ea9f83efae04e5e6f5f81b55cb9eac222/.github/PULL_REQUEST_TEMPLATE.md) always, please?
- Is this PR draft still?

**Comment by sleeeto** [comment]
@ybiquitous 
- used PULL_REQUEST_TEMPLATE.md
- switched open PR.

**Comment by sleeeto** [comment]
@ybiquitous I changed #9965 . And is this OK ?

**Comment by ybiquitous** [comment]
No. This repository is public, so please don't refer to private repositories.
I've changed the PR description.

**Review by ybiquitous — APPROVED** [review]
LGTM 👍

**Pull request merged**
