### PR TITLE
Add document URL to metrics runners

### PR DESCRIPTION
**Pull request by dev-yakuza**
> Explain a summary, purpose, or background for this change.

We've written the documentation about metrics runners(`Metrics Code Clone`, `Metrics Complexity` and `Metrics File Info`) on [Sider Documentation](https://help.sider.review/getting-started/code-quality).

So, I added the documentation URL to the metrics runners.

> Refer related issues or pull requests (e.g. `Close #123` or `None`).

https://github.com/sider/sider-docs/issues/613

> Check the following if needed.

- [x] Add a new entry to [CHANGELOG.md](https://github.com/sider/runners/blob/master/CHANGELOG.md) if this change is notable.

### CODE REVIEW

**Comment by dev-yakuza** [comment]
@suetsuguk @ybiquitous 
Is it better to create new pages like [Secret Scan
](https://help.sider.review/tools/others/secret-scan) for the documentation URL? 🤔

**Comment by ybiquitous** [comment]
I think no problems that we have one page: https://help.sider.review/getting-started/code-quality

**Review by ybiquitous — APPROVED** [review]
LGTM 👍🏼 

Can you add a changelog entry, please?

**Review by ybiquitous — APPROVED** [review]
Thanks!

**Review by suetsuguk — APPROVED** [review]
LGTM. Thank you.
I myself missed adding URL to this file.

**Pull request merged**
