### PR TITLE
[Refactor] Remove unused `Changes#untracked_paths` method

### PR DESCRIPTION
**Pull request by ybiquitous**
This method seems for symlinks but Sider does not analyze them.

Note: This PR is preparation for the issue #951.

### CODE REVIEW

**Comment by ybiquitous** [comment]
@yykamei Can I merge this PR?

**Comment by ybiquitous** [comment]
I merge this to continue #958.
I think this is NOT breaking, but please mention to me if you have any concerns.

**Comment by yykamei** [comment]
Sorry to be late. I read the code and thought it seemed good. Nice work :clap:

**Comment by ybiquitous** [comment]
Thank you! 😺

**Pull request merged**
