### PR TITLE
[Rails Best Practices] Fix invalid line number

### PR DESCRIPTION
**Pull request by ybiquitous**
> Explain a summary, purpose, or background for this change.

I've patched the bug of Rails Best Practices. But the patched version is not released yet.

> Link related issues, e.g. "Fix #<ISSUE_ID>", "Related to #<ISSUE_ID>", or "None."

Related to #1216

> Check the following items.

- [x] Add a new [changelog](https://github.com/sider/runners/blob/master/CHANGELOG.md) entry if this change is notable.

### CODE REVIEW

**Comment by ybiquitous** [comment]
Yes, I think so. How about the commit a2c84e2e?

**Comment by ybiquitous** [comment]
@yykamei ping? https://github.com/sider/runners/pull/1232#issuecomment-649986981

**Comment by yykamei** [comment]
OK, it looks good

**Comment by ybiquitous** [comment]
Thanks. 👍

**Pull request merged**
