### PR TITLE
Use an ssh_key of Runners and delete a smoke test on gometalinter

### PR DESCRIPTION
**Pull request by yykamei**
We deleted the repository sider/go_private_library.
It's not necessary to use a private repository in this test, so, I set a deploy key on sider/runners.
Also, I deleted the smoke test `private_dependency` from `gometalinter`.

### CODE REVIEW

**Comment by ybiquitous** [comment]
@yykamei Thanks a lot! Can we fix also the failed smoke test in the same way?

https://github.com/sider/runners/pull/937/checks?check_run_id=557865602#step:8:33

**Comment by yykamei** [comment]
> @yykamei Thanks a lot! Can we fix also the failed smoke test in the same way?

Oh, I just deleted it. What do you think?

**Comment by ybiquitous** [comment]
No problem. 👍

**Comment by ybiquitous** [comment]
It seems better if we could change the PR title. 😏

**Comment by yykamei** [comment]
Thank you. To supplement the reason I deleted the test, we are going to drop the support of Go Meta Linter on #764, so I didn't care about the deprecated smoke test.

**Pull request merged**
