### PR TITLE
[Slim-Lint] Set up recommended ruleset

### PR DESCRIPTION
**Pull request by ybiquitous**
> Explain a summary, purpose, or background for this change.

Slim-Lint's default value of the rule `LineLength` is too strict:
<https://github.com/sds/slim-lint/blob/v0.20.2/config/default.yml>

So, this change aims to loosen the value via our recommended ruleset.

> Link related issues or pull requests.

Follow-up of #2014

> Check the following if needed.

- [x] Add a new entry to [CHANGELOG.md](https://github.com/sider/runners/blob/master/CHANGELOG.md) if this change is notable.

### CODE REVIEW

**Comment by ybiquitous** [comment]
@yykamei Does this change make sense? When I test Slim-Lint in our project, too many `LineLength` issues are detected. 😓

**Comment by ybiquitous** [comment]
(It seems we need to prepare such recommended ruleset also for HAML-Lint... 🤔 )

**Review by yykamei — APPROVED** [review]
LGTM

**Comment by ybiquitous** [comment]
Thanks. What do you think about <https://github.com/sider/runners/pull/2046#issuecomment-776489055>?

**Comment by ybiquitous** [comment]
OK, I'll address HAML-Lint also.

**Pull request merged**
