### PR TITLE
Drop support for Rails Best Practices

### PR DESCRIPTION
**Pull request by radomirbosak**
Fixes: #2320

### CODE REVIEW

**Comment by radomirbosak** [comment]
Language tool download from https://languagetool.org/download/LanguageTool-5.4.zip
fails with `403 Forbidden` and returns this page
langtool-cloudfare

If I do the same with chrome, it succeeds. A simple curl no longer suffices. Due to cloudfare protection.

**Comment by radomirbosak** [comment]
Also what do I do with the unresponsive `build (rails_best_practices)` check? Do I need to remove rails_best_practices from `build.yml` first in a separate PR, so that it's not checked?

**Comment by ybiquitous** [comment]
Yes, we can remove `build (rails_best_practices)` check from the protected branch. 👍🏼

**Review by ybiquitous — APPROVED** [review]
Looks good! 👍🏼

**Review by dev-yakuza — APPROVED** [review]
LGTM 👍

**Review by suetsuguk — APPROVED** [review]
LGTM. Thank you.

**Comment by suetsuguk** [comment]
Go to Settings - Branches - Branch protection rules and edit `master` to remove the `build (rails_best_practices)` requirement from the list.

**Comment by radomirbosak** [comment]
> Go to Settings - Branches - Branch protection rules and edit master to remove the build (rails_best_practices) requirement from the checks.

Thank you, removed. I will proceed with merge.

**Pull request merged**
