### PR TITLE
[Refactor] Move processors directory

### PR DESCRIPTION
**Pull request by ybiquitous**
E.g. `NodeHarness::Runners::Checkstyle::Processor` -> `NodeHarness::Processor::Checkstyle`

See also #59

### CODE REVIEW

**Comment by ybiquitous** [comment]
@yykamei Could you please review this lightly if you have time?

**Comment by yykamei** [comment]
I'm curious why you updated runners without nesting.

I know the following causes a TypeError:

```ruby
class A
end

module A
  class R1
  end
end
```

From my understanding, `Processor` in this project is declared as a class, so all nested classes are declared with this syntax. Right?

```ruby
class A
end

class A::R1
end
```

**Comment by ybiquitous** [comment]
Yes, I understand this is just a stylistic issue because the all test passed.
Also, I don't like personally deeply nesting, but one level nesting seems to be reasonable like this:

```ruby
module NodeHarness
  class Processor::Cppcheck < Processor
  end
end
```

What do you think about this?

**Comment by yykamei** [comment]
Yeah, I agree. I just wanted to know. It's reasonable.

**Comment by ybiquitous** [comment]
Thanks. I will update them. 💪

**Comment by ybiquitous** [comment]
I will update all files via this script:

```ruby
file = ARGV[0] or abort "Require file!"

lines = File.readlines(file, chomp: true).map do |line|
  "  #{line}".gsub("NodeHarness::", "") unless line.empty?
end
lines.prepend "module NodeHarness"
lines.append "end"

File.write file, (lines.join("\n") + "\n")
```

**Pull request merged**
