### PR TITLE
Fix check_skip to support multiple lines of commit messages

### PR DESCRIPTION
**Pull request by yykamei**
I want to fix the error.

https://github.com/sider/runners/runs/499924076?check_suite_focus=true

### CODE REVIEW

**Comment by ybiquitous** [comment]
If you want to try `push` on this PR, you can write temporarily as follow:

```diff
on:
  push:
-   branches: ["master"]
+   branches: ["**"]
```

**Comment by yykamei** [comment]
> If you want to try `push` on this PR, you can write temporarily as follow:

Nice!

**Comment by yykamei** [comment]
:man_shrugging: Let's merge!

**Comment by yykamei** [comment]
Succeeded :tada: 
https://github.com/sider/runners/runs/500025894

**Comment by ybiquitous** [comment]
Great! Thank you so much! 😊

**Pull request merged**
