### PR TITLE
Bump devon_rex images from 2.45.11 to 2.46.0

### PR DESCRIPTION
**Pull request by gnakagaw**
This change is created by:
```
$ bundle exec rake bump:devon_rex'[2.46.0]'
```

See also:
- https://github.com/sider/devon_rex/releases/tag/2.46.0
- https://github.com/sider/devon_rex/blob/2.46.0/CHANGELOG.md

### Issues or Pull Requests

Nothing

### Checklist

- [x] Add a new entry to [CHANGELOG.md](https://github.com/sider/runners/blob/master/CHANGELOG.md) if this change is notable.

### CODE REVIEW

**Comment by radomirbosak** [comment]
For flake8, it looks like in the "sandbox_django" smoke test, the `flake8` command started returning exit code 1.

**Comment by radomirbosak** [comment]
I think flake8 is hitting [this issue](https://github.com/PyCQA/flake8/issues/1372) with python3.10, so we should update flake8 to version at least 4.0.0 

I was able to reproduce the AttributeError on my local machine:
```shell
$ python3.10 -m pip install flake8==3.9.2
...
$ python3.10 -m flake8
multiprocessing.pool.RemoteTraceback: 
...
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 870, in next
    raise value
AttributeError: 'int' object has no attribute 'rstrip'


$ python3.10 -m pip install flake8==4.0.1
...
$ python3.10 -m flake8
[successfully reports issues]
```

**Comment by gnakagaw** [comment]
I confirmed that Updating Flake8 > 4.0.0 resolve the error. But, I face another smoke test errors. They seems to be caused by some ruleset changes. I'll fix that.

**Comment by radomirbosak** [comment]
I believe SwiftLint check errors can be resolved by updating to SwiftLint 0.45.0
https://github.com/sider/runners/pull/2765

**Comment by gnakagaw** [comment]
Flake 8 error will be fixed by updating Flake 8 to 4.0.1 
#2751

**Pull request merged**
