### PR TITLE
Remove unused HTTP and File workspace

### LINKED ISSUE #1146: Run smoke tests on Git workspace
Now, smoke tests are run on `Workspace::File`, but this is not used on production.
Actually used class is `Workspace::Git`.

### PR DESCRIPTION
**Pull request by ybiquitous**
> Explain a summary, purpose, or background for this change.

`Workspace::HTTP` and `Workspace::File` classes have no longer used. (Only `Workspace::Git` is used)
This pull request aims to reduce the code.

> Link related issues, e.g. "Fix #<ISSUE_ID>", "Related to #<ISSUE_ID>", or "None."

Fix #1146 

> Check the following items.

- [] ~~Add a new [changelog](https://github.com/sider/runners/blob/master/CHANGELOG.md) entry if this change is notable.~~
  → Internal change.

### CODE REVIEW

**Comment by ybiquitous** [comment]
The smoke test depends on `Workspace::File`. See below:

https://github.com/sider/runners/blob/2203cb38aec088cc6d2ecf3498c441971d744702/lib/runners/testing/smoke.rb#L125

**Comment by ybiquitous** [comment]
My suggestion for the smoke test:

1. Create a bare repository in localhost for each smoke test directory, e.g. `test/smokes/goodcheck/success/`
2. Commit and push all the files in each smoke test directory to the created bare repository.
3. Mount the bare repository's directory with `docker run`.
4. Pass `file:///git_bare_directory` as Git URL to `docker run`.

**Comment by yykamei** [comment]
Thank you :pray:  I wanted to remove them.

**Comment by ybiquitous** [comment]
I've improved the smoke test output via the [`rainbow`](https://github.com/sickill/rainbow) gem

Normal:

image

With `DEBUG` (new environment variable):

image

**Comment by ybiquitous** [comment]
@yykamei This PR is in progress yet, but I think almost code is done to change. (I'm fixing the smoke tests).

So, could you please review the code except for the smoke tests?

**Comment by ybiquitous** [comment]
Thank you!

**Comment by ybiquitous** [comment]
CI passed! 🎉

**Pull request merged**
