### PR TITLE
Include :git_blame_info in `Issue` instances

### PR DESCRIPTION
**Pull request by yykamei**
Make Runners add `:git_blame_info` for every issue.

Also, I renamed the API `Workspace#git_blame_info` to
`Workspace#range_git_blame_info`, and declare `Processor#git_blame_info`
because I want to relate the method name with the `GitBlameInfo` class.

### CODE REVIEW

**Comment by yykamei** [comment]
@ybiquitous I added `git_blame_info` in each processor. What do you think?

**Comment by ybiquitous** [comment]
Cannot you calculate `git_blame_info` within `Issue` class?

**Comment by yykamei** [comment]
Maybe. I have to make `Issue` depend on `Workspace` if so.

**Comment by ybiquitous** [comment]
Yes, for example:

```ruby
class Issue
  def initialize(path:, location:, workspace:)
    @git_blame_info = workspace.range_git_blame_info(path, location.start_line, location.end_line || location.start_line).last
  end
end
```

I think each processor can decrease its implementation cost.

```ruby
Issue.new(
  path: path,
  location: loc,
  id: "#{warning[:warning_type]}-#{warning[:warning_code]}",
  message: warning[:message],
  links: [warning[:link]],
  git_blame_info: git_blame_info(warning[:file], line), #<= Read attributes mutiple times. Not DRY.
)
```

**Comment by yykamei** [comment]
I try.

**Comment by yykamei** [comment]
Do you have an idea about passing an instance of `Workspace` to `Issue`?

**Comment by ybiquitous** [comment]
I think as follow:

```ruby
Issue.new(
  path: path,
  location: loc,
  id: "#{warning[:warning_type]}-#{warning[:warning_code]}",
  message: warning[:message],
  links: [warning[:link]],
  workspace: workspace,
)
```

**Comment by ybiquitous** [comment]
I'm worried also if a performance issue will raise, which is calling `shell.capture3!("git", "blame")` for each issue.
It is similar to the N+1 problem and may overflow trace logs.

**Comment by yykamei** [comment]
Yes, I thought the performance issues, too. However, I cannot estimate how much the problem is.

By the way, I'm worried about `Issue` depends on `Workspace`.  Anyway, I'll do another implementation. Close this PR.

**Comment by ybiquitous** [comment]
> I'm worried about `Issue` depends on `Workspace`.

Surely, I think also it's not so good design 😅

**Comment by yykamei** [comment]
Thank you for your review!

**Comment by yykamei** [comment]
I might be able to mitigate the N+1 problem by calling git-blame(1) for filtered issues after calling `Results::Success#filter_issues`. It's not a perfect solution to avoid N+1, but I could reduce the traces with it. I implemented this with #655.

**Comment by ybiquitous** [comment]
> It's not a perfect solution to avoid N+1

Yes, it seems no other way... 🤷‍♂

**Pull request closed without merging**
